# Generated by Django 5.1.7 on 2025-04-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_judgenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
