# Generated by Django 5.1.7 on 2025-04-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_interest_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('assigning', 'Referee Assignment In Progress'), ('in_review', 'In Review'), ('reviewed', 'Review Concluded'), ('published', 'Published')], default='submitted', max_length=20),
        ),
    ]
